package session

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	plogger "github.com/pancake-lee/pgo/pkg/plogger"
)

const (
	focusInScript    = "focus-log.sh"
	focusOutScript   = "focus-log-out.sh"
	focusHistoryFile = "focus_history.log"
)

// focusScriptContent is the inline shell script that writes focus-in events
// to the focus history log. It is auto-created by SetupFocusHooks.
const focusScriptContent = `#!/bin/bash
# Auto-generated by pflow serve. Do not edit manually.
# Logs tmux focus events for active-time tracking.
echo "$(date +%s%N 2>/dev/null || date +%s000000000)|focus-in|$1|none|none|0" >> ~/.pflow/focus_history.log
`

// focusOutScriptContent writes focus-out events.
const focusOutScriptContent = `#!/bin/bash
# Auto-generated by pflow serve. Do not edit manually.
echo "$(date +%s%N 2>/dev/null || date +%s000000000)|focus-out|$1|none|none|0" >> ~/.pflow/focus_history.log
`

// SetupFocusHooks creates the focus-logging scripts and registers tmux
// hooks so that session focus changes are tracked automatically.
//
// Hooks registered:
//   - client-attached: user attaches to a pflow session → focus-in
//   - client-session-changed: user switches to a different session → focus-in
//   - client-detached: user detaches from a session → focus-out
//
// Only pflow-managed sessions (those with a pflow- prefix) are tracked.
func SetupFocusHooks() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("focus hooks: cannot find home: %w", err)
	}

	pflowDir := filepath.Join(home, ".pflow")
	if err := os.MkdirAll(pflowDir, 0755); err != nil {
		return fmt.Errorf("focus hooks: cannot create ~/.pflow: %w", err)
	}
	if err := ensureFocusEventsConfig(filepath.Join(home, ".tmux.conf")); err != nil {
		return err
	}
	if err := enableTmuxFocusEvents(); err != nil {
		return err
	}

	// Write focus-in script
	inPath := filepath.Join(pflowDir, focusInScript)
	if err := os.WriteFile(inPath, []byte(focusScriptContent), 0755); err != nil {
		return fmt.Errorf("focus hooks: write %s: %w", inPath, err)
	}

	// Write focus-out script
	outPath := filepath.Join(pflowDir, focusOutScript)
	if err := os.WriteFile(outPath, []byte(focusOutScriptContent), 0755); err != nil {
		return fmt.Errorf("focus hooks: write %s: %w", outPath, err)
	}

	// client-focus-* describes actual terminal-window focus. Older tmux
	// releases simply reject these hooks, which leaves time estimation on its
	// existing message-based fallback path.
	if err := setTmuxHook("client-focus-in", focusHookCommand(inPath)); err != nil {
		return fmt.Errorf("focus hooks: set client-focus-in (tmux 3.3+ required): %w", err)
	}
	if err := setTmuxHook("client-focus-out", focusHookCommand(outPath)); err != nil {
		return fmt.Errorf("focus hooks: set client-focus-out (tmux 3.3+ required): %w", err)
	}

	plogger.Infof("focus hooks: registered tmux hooks, scripts at %s", pflowDir)
	return nil
}

// ensureFocusEventsConfig appends exactly one focus-events setting when the
// user has not configured it. Existing on/off settings and unrelated config
// are preserved verbatim.
func ensureFocusEventsConfig(path string) error {
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("focus hooks: read %s: %w", path, err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.Contains(trimmed, "focus-events") {
			return nil
		}
	}
	content := strings.TrimRight(string(data), "\n")
	if content != "" {
		content += "\n"
	}
	content += "# Added by pflow for accurate active-time tracking.\nset -g focus-events on\n"
	tmpPath := path + ".pflow-tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("focus hooks: write %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("focus hooks: replace %s: %w", path, err)
	}
	return nil
}

func enableTmuxFocusEvents() error {
	cmd := exec.Command("tmux", "set-option", "-g", "focus-events", "on")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("focus hooks: enable tmux focus-events: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// TeardownFocusHooks removes the tmux focus hooks registered by SetupFocusHooks.
// The log file and scripts are left in place (harmless, may be re-used).
func TeardownFocusHooks() {
	for _, hook := range []string{"client-focus-in", "client-focus-out"} {
		// Remove the first matching hook entry. tmux set-hook -gu removes
		// the hook at index 0; we set ours at index 0 so this works.
		cmd := exec.Command("tmux", "set-hook", "-gu", hook)
		if out, err := cmd.CombinedOutput(); err != nil {
			// Hook might not exist — not an error
			plogger.Debugf("focus hooks: teardown %s: %v (output: %s)", hook, err, strings.TrimSpace(string(out)))
		}
	}
	plogger.Infof("focus hooks: removed tmux hooks")
}

func focusHookCommand(scriptPath string) string {
	return fmt.Sprintf("run-shell \"case '#{session_name}' in pflow-*) %s '#{session_name}' ;; esac\"", scriptPath)
}

// setTmuxHook registers a single tmux hook via `tmux set-hook -g`.
// The -g flag makes it global (applies to all sessions).
func setTmuxHook(hookName, command string) error {
	cmd := exec.Command("tmux", "set-hook", "-g", hookName, command)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w (output: %s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// FocusLogPath returns the path to the focus history log file.
func FocusLogPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".pflow", focusHistoryFile), nil
}
