package session

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	plogger "github.com/pancake-lee/pgo/pkg/plogger"
)

const (
	focusInScript    = "focus-log.sh"
	focusOutScript   = "focus-log-out.sh"
	focusHistoryFile = "focus_history.log"
)

// focusScriptContent is the inline shell script that writes focus-in events
// to the focus history log. It is auto-created by SetupFocusHooks.
const focusScriptContent = `#!/bin/bash
# Auto-generated by pflow serve. Do not edit manually.
# Logs tmux focus events for active-time tracking.
echo "$(date +%s%N 2>/dev/null || date +%s000000000)|focus-in|$1|none|none|0" >> ~/.pflow/focus_history.log
`

// focusOutScriptContent writes focus-out events.
const focusOutScriptContent = `#!/bin/bash
# Auto-generated by pflow serve. Do not edit manually.
echo "$(date +%s%N 2>/dev/null || date +%s000000000)|focus-out|$1|none|none|0" >> ~/.pflow/focus_history.log
`

// SetupFocusHooks creates the focus-logging scripts and registers tmux
// hooks so that session focus changes are tracked automatically.
//
// Hooks registered:
//   - client-attached: user attaches to a pflow session → focus-in
//   - client-session-changed: user switches to a different session → focus-in
//   - client-detached: user detaches from a session → focus-out
//
// Only pflow-managed sessions (those with a pflow- prefix) are tracked.
func SetupFocusHooks() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("focus hooks: cannot find home: %w", err)
	}

	pflowDir := filepath.Join(home, ".pflow")
	if err := os.MkdirAll(pflowDir, 0755); err != nil {
		return fmt.Errorf("focus hooks: cannot create ~/.pflow: %w", err)
	}

	// Write focus-in script
	inPath := filepath.Join(pflowDir, focusInScript)
	if err := os.WriteFile(inPath, []byte(focusScriptContent), 0755); err != nil {
		return fmt.Errorf("focus hooks: write %s: %w", inPath, err)
	}

	// Write focus-out script
	outPath := filepath.Join(pflowDir, focusOutScript)
	if err := os.WriteFile(outPath, []byte(focusOutScriptContent), 0755); err != nil {
		return fmt.Errorf("focus hooks: write %s: %w", outPath, err)
	}

	// Register tmux hooks. Each hook filters for pflow-* sessions
	// and delegates to the appropriate logging script.

	// client-attached: user opens a terminal and attaches to a session
	if err := setTmuxHook("client-attached",
		fmt.Sprintf("run-shell \"case '#{session_name}' in pflow-*) %s '#{session_name}' ;; esac\"", inPath)); err != nil {
		return fmt.Errorf("focus hooks: set client-attached: %w", err)
	}

	// client-session-changed: user switches session within an existing client
	if err := setTmuxHook("client-session-changed",
		fmt.Sprintf("run-shell \"case '#{session_name}' in pflow-*) %s '#{session_name}' ;; esac\"", inPath)); err != nil {
		return fmt.Errorf("focus hooks: set client-session-changed: %w", err)
	}

	// client-detached: user closes terminal or detaches
	if err := setTmuxHook("client-detached",
		fmt.Sprintf("run-shell \"case '#{session_name}' in pflow-*) %s '#{session_name}' ;; esac\"", outPath)); err != nil {
		return fmt.Errorf("focus hooks: set client-detached: %w", err)
	}

	plogger.Infof("focus hooks: registered tmux hooks, scripts at %s", pflowDir)
	return nil
}

// TeardownFocusHooks removes the tmux focus hooks registered by SetupFocusHooks.
// The log file and scripts are left in place (harmless, may be re-used).
func TeardownFocusHooks() {
	for _, hook := range []string{"client-attached", "client-session-changed", "client-detached"} {
		// Remove the first matching hook entry. tmux set-hook -gu removes
		// the hook at index 0; we set ours at index 0 so this works.
		cmd := exec.Command("tmux", "set-hook", "-gu", hook)
		if out, err := cmd.CombinedOutput(); err != nil {
			// Hook might not exist — not an error
			plogger.Debugf("focus hooks: teardown %s: %v (output: %s)", hook, err, strings.TrimSpace(string(out)))
		}
	}
	plogger.Infof("focus hooks: removed tmux hooks")
}

// setTmuxHook registers a single tmux hook via `tmux set-hook -g`.
// The -g flag makes it global (applies to all sessions).
func setTmuxHook(hookName, command string) error {
	cmd := exec.Command("tmux", "set-hook", "-g", hookName, command)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w (output: %s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// FocusLogPath returns the path to the focus history log file.
func FocusLogPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".pflow", focusHistoryFile), nil
}
